[General]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\x63\0\0\0M\0\0\x2o\0\0\x2\xf4\0\0\0\x63\0\0\0k\0\0\x2o\0\0\x2\xf4\0\0\0\0\0\0\0\0\a\x80)
locale=
mailSupport=mailto:support@4kdownload.com
socialReferrer=http://www.4kdownload.com/
socialUrl=http://www.4kdownload.com/
socialVia=4kdownload
state=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x2\r\0\0\x2\x30\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x1\0\0\0\x2\0\0\0\x1\xff\xff\xff\xff\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)
web="http://www.4kdownload.com?source=videodownloader&redirect-locale=ru"
webBuy="http://www.4kdownload.com/buy/videodownloader?source=videodownloader&redirect-locale=ru"
webDonate="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KVE5JR5PPWNJE"
webFacebook=http://www.facebook.com/4kdownload
webFeedback="http://feedback.4kdownload.com?source=videodownloader&redirect-locale=ru"
webHelp="http://www.4kdownload.com/howto/howto-download-youtube-video?source=videodownloader&redirect-locale=ru"
webThanks="http://www.4kdownload.com/thanks-for-installing?source=videodownloader&redirect-locale=ru"
webTwitter=https://twitter.com/4kdownload
webVideoTutorial="http://www.4kdownload.com/video/how-to-use-4k-video-downloader?source=videodownloader&redirect-locale=ru"
webVimeo=https://vimeo.com/4kdownloadtv
webYouTube=https://www.youtube.com/user/4KDownload

[Agreement]
eula_v1=true

[Analytics]
clientId=765ed9f0-b9ec-4ffa-87f3-f11b8ea17686

[Dialog]
dirDialogDirectory=/home/serii/\x412\x438\x434\x435\x43e
openDialogDirectory=/home/serii/\x412\x438\x434\x435\x43e
saveDialogDirectory=/home/serii/\x412\x438\x434\x435\x43e

[Download]
downloadedItemsDb=/home/serii/.local/share/4kdownload.com/4K Video Downloader/4K Video Downloader/c34d3f89-4dbc-4d55-b795-fec0af8b7c46.sqlite

[Gamification]
download=1

[License]
licenseBody=@ByteArray()

[Notification]
lastVersion=4.7.3.2742
runCount=1

[Settings]
achievementsEnabled=true
askPlaylistOrClip=true
askQuit=true
askRemoveSubscription=true
betaAccessEnabled=false
deleteConfirmation=true
downloadFormat="{\n\"id\": \"format_youtube_133\",\n\"container\": \"MP4\",\n\"video_codec\": \"H264\",\n\"audio_codec\": \"\",\n\"video_resolution\": \"240p\",\n\"overall_bitrate\": 270000,\n\"audio_bitrate\": 0,\n\"status\": \"Experimental\",\n\"dimension\": \"2D\",\n\"for_audio_conversion\": 0\n}"
embedSubtitles=false
exportEnabled=false
folderEnabled=false
m3uEnabled=false
notificationEnabled=true
numerationEnabled=false
originalAudioBitrate=false
outputAudioBitrate=-1
outputContainer=0
outputPath=/home/serii/\x412\x438\x434\x435\x43e/4K Video Downloader
progressEnabled=true
proposeDownloadChannel=true
proxyEnabled=false
proxyLogin=
proxyPassword=
proxyPort=
proxyServer=
proxyType=0
removeCompletedDownloads=false
skipDuplicates=false
soundEnabled=false
speedLimitIndex=0
subtitlesOptions={\n    \"s\": [\n    ]\n}\n
tagsEnabled=true
threadIndex_v2=1
