[General]
hotkey=Ctrl+Alt+Space
showTray=true
telemetry=true

[org.albert.extension.applications]
enabled=true

[org.albert.extension.chromebookmarks]
enabled=true

[org.albert.extension.externalextensions]
enabled=false

[org.albert.extension.files]
enabled=true

[org.albert.extension.firefoxbookmarks]
enabled=false

[org.albert.extension.hashgenerator]
enabled=false

[org.albert.extension.mpris]
enabled=false

[org.albert.extension.ssh]
enabled=false

[org.albert.extension.system]
enabled=false

[org.albert.extension.terminal]
enabled=false

[org.albert.extension.websearch]
enabled=false

[org.albert.frontend.widgetboxmodel]
alwaysOnTop=true
clearOnHide=false
displayIcons=true
displayScrollbar=true
displayShadow=true
hideOnClose=true
hideOnFocusLoss=true
itemCount=10
showCentered=true
theme=Numix
