for(var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},n="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,q=["Array","prototype","fill"],r=0;r<q.length-1;r++){var u=q[r];u in n||(n[u]={});n=n[u]}
var v=q[q.length-1],w=n[v],x=function(a){return a?a:function(a,c,g){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==g||g>b)g=b;g=Number(g);0>g&&(g=Math.max(0,b+g));for(c=Number(c||0);c<g;c++)this[c]=a;return this}}(w);x!=w&&null!=x&&aa(n,v,{configurable:!0,writable:!0,value:x});function y(){var a=[["edge",/Edge\/([0-9\._]+)/],["chrome",/Chrom(?:e|ium)\/([0-9\.]+)(:?\s|$)/],["firefox",/Firefox\/([0-9\.]+)(?:\s|$)/],["opera",/Opera\/([0-9\.]+)(?:\s|$)/],["ie",/Trident\/7\.0.*rv\:([0-9\.]+)\).*Gecko$/],["ie",/MSIE\s([0-9\.]+);.*Trident\/[4-7].0/],["ie",/MSIE\s(7\.0)/],["bb10",/BB10;\sTouch.*Version\/([0-9\.]+)/],["android",/Android\s([0-9\.]+)/],["ios",/iPad\;\sCPU\sOS\s([0-9\._]+)/],["ios",/iPhone\;\sCPU\siPhone\sOS\s([0-9\._]+)/],["safari",/Safari\/([0-9\._]+)/]],b,c=[];
for(b=0;b<a.length;b++){var g=b;var l=a[b];l=l.concat(l[1].exec(navigator.userAgent));a[g]=l;a[b][2]&&c.push(a[b])}for(b=(a=c[0])&&a[3].split(/[._]/).slice(0,3);b&&3>b.length;)b.push("0");c={};c.name=a&&a[0];c.version=b&&b.join(".");c.versionInt=parseInt(c.version,10);return c};window._gaq=window._gaq||[];var ba={oa:function(a){return a+Math.random()},Ja:function(a){for(var b=a.length,c,g;0!==b;)g=Math.floor(Math.random()*b),--b,c=a[b],a[b]=a[g],a[g]=c;return a},Ia:function(a,b){return Math.floor(Math.random()*(b-a+1)+a)}},z={extend:function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.S=b.prototype}},A={u:function(a){return chrome.i18n.getMessage(a)}};function B(a){B.S.constructor.apply(this,arguments);this.create()}z.extend(B,function(a){this.b=a;this.v=null});B.prototype.create=function(){var a=this,b={type:"progress",title:"Lightshot",message:A.u("screenshot_plugin_uploading_window_capt"),iconUrl:"img/icon256.png",buttons:[{title:A.u("screenshot_plugin_cancel")}],isClickable:!0,progress:0};"chrome"==y().name&&50<=y().versionInt&&(b.requireInteraction=!0);delete b.buttons;chrome.notifications.create(this.b,b,function(){a.v="uploading"})};
B.prototype.update=function(a){"progress"===a.type&&a.progress||"success"===a.type&&a.message&&C.sendMessage({name:E,id:this.b})};
function ca(){function a(a){chrome.notifications.clear(a,function(){});delete b[a]}var b={};chrome.notifications.onClicked.addListener(function(a){a=b[a];"success"===a.v&&C.sendMessage({name:E,id:a.b})});chrome.notifications.onButtonClicked.addListener(function(a,g){a=b[a];"uploading"===a.v&&0===g?C.sendMessage({name:F,id:a.b}):"success"===a.v?0===g?C.sendMessage({name:G,id:a.b}):1===g&&C.sendMessage({name:E,id:a.b}):"failed"===a.v&&(0===g?C.sendMessage({name:H,id:a.b}):1===g&&C.sendMessage({name:F,
id:a.b}))});return{ja:function(c){a(c);b[c]=new B(c)},T:function(a,g){b[a].update(g)},D:a}};var I=function(){function a(){return"https://api.prntscr.com/v1.1/"}return{save:function(b,c){b&&"undefined"!=typeof b&&"undefined"!=typeof b.img_url&&$.ajax({type:"POST",url:a(),data:JSON.stringify({jsonrpc:"2.0",id:1,method:"save",params:b}),dataType:"json",beforeSend:function(a){a.setRequestHeader("Content-Type","application/x-www-form-urlencoded")},complete:function(a){a.responseJSON&&"undefined"!=typeof a.responseJSON&&"undefined"!=typeof a.responseJSON.result?c(a.responseJSON.result):c(null)}})},
ia:function(b,c,g,l){b&&"undefined"!=typeof b&&$.ajax({type:"POST",url:a(),data:JSON.stringify({jsonrpc:"2.0",id:1,method:"attach_extension",params:{auth:b,app_id:c,app_description:g}}),dataType:"json",beforeSend:function(a){a.setRequestHeader("Content-Type","application/x-www-form-urlencoded")},complete:function(a){a.responseJSON&&"undefined"!=typeof a.responseJSON&&"undefined"!=typeof a.responseJSON.result?l(a.responseJSON.result):l(null)}})},ka:function(b,c,g){b&&"undefined"!=typeof b&&c&&"undefined"!=
typeof c&&$.ajax({type:"POST",url:a(),data:JSON.stringify({jsonrpc:"2.0",id:1,method:"detach_application_ext",params:{app_id:b,app_token:c}}),dataType:"json",beforeSend:function(a){a.setRequestHeader("Content-Type","application/x-www-form-urlencoded")},complete:function(a){a.responseJSON&&"undefined"!=typeof a.responseJSON&&"undefined"!=typeof a.responseJSON.result?g(a.responseJSON.result):g(null)}})},ra:a}}();if("function"!==typeof J)var J=function(){function a(a,k){var h=a[0],e=a[1],d=a[2],f=a[3];h=c(h,e,d,f,k[0],7,-680876936);f=c(f,h,e,d,k[1],12,-389564586);d=c(d,f,h,e,k[2],17,606105819);e=c(e,d,f,h,k[3],22,-1044525330);h=c(h,e,d,f,k[4],7,-176418897);f=c(f,h,e,d,k[5],12,1200080426);d=c(d,f,h,e,k[6],17,-1473231341);e=c(e,d,f,h,k[7],22,-45705983);h=c(h,e,d,f,k[8],7,1770035416);f=c(f,h,e,d,k[9],12,-1958414417);d=c(d,f,h,e,k[10],17,-42063);e=c(e,d,f,h,k[11],22,-1990404162);h=c(h,e,d,f,k[12],7,1804603682);
f=c(f,h,e,d,k[13],12,-40341101);d=c(d,f,h,e,k[14],17,-1502002290);e=c(e,d,f,h,k[15],22,1236535329);h=g(h,e,d,f,k[1],5,-165796510);f=g(f,h,e,d,k[6],9,-1069501632);d=g(d,f,h,e,k[11],14,643717713);e=g(e,d,f,h,k[0],20,-373897302);h=g(h,e,d,f,k[5],5,-701558691);f=g(f,h,e,d,k[10],9,38016083);d=g(d,f,h,e,k[15],14,-660478335);e=g(e,d,f,h,k[4],20,-405537848);h=g(h,e,d,f,k[9],5,568446438);f=g(f,h,e,d,k[14],9,-1019803690);d=g(d,f,h,e,k[3],14,-187363961);e=g(e,d,f,h,k[8],20,1163531501);h=g(h,e,d,f,k[13],5,-1444681467);
f=g(f,h,e,d,k[2],9,-51403784);d=g(d,f,h,e,k[7],14,1735328473);e=g(e,d,f,h,k[12],20,-1926607734);h=b(e^d^f,h,e,k[5],4,-378558);f=b(h^e^d,f,h,k[8],11,-2022574463);d=b(f^h^e,d,f,k[11],16,1839030562);e=b(d^f^h,e,d,k[14],23,-35309556);h=b(e^d^f,h,e,k[1],4,-1530992060);f=b(h^e^d,f,h,k[4],11,1272893353);d=b(f^h^e,d,f,k[7],16,-155497632);e=b(d^f^h,e,d,k[10],23,-1094730640);h=b(e^d^f,h,e,k[13],4,681279174);f=b(h^e^d,f,h,k[0],11,-358537222);d=b(f^h^e,d,f,k[3],16,-722521979);e=b(d^f^h,e,d,k[6],23,76029189);
h=b(e^d^f,h,e,k[9],4,-640364487);f=b(h^e^d,f,h,k[12],11,-421815835);d=b(f^h^e,d,f,k[15],16,530742520);e=b(d^f^h,e,d,k[2],23,-995338651);h=l(h,e,d,f,k[0],6,-198630844);f=l(f,h,e,d,k[7],10,1126891415);d=l(d,f,h,e,k[14],15,-1416354905);e=l(e,d,f,h,k[5],21,-57434055);h=l(h,e,d,f,k[12],6,1700485571);f=l(f,h,e,d,k[3],10,-1894986606);d=l(d,f,h,e,k[10],15,-1051523);e=l(e,d,f,h,k[1],21,-2054922799);h=l(h,e,d,f,k[8],6,1873313359);f=l(f,h,e,d,k[15],10,-30611744);d=l(d,f,h,e,k[6],15,-1560198380);e=l(e,d,f,h,
k[13],21,1309151649);h=l(h,e,d,f,k[4],6,-145523070);f=l(f,h,e,d,k[11],10,-1120210379);d=l(d,f,h,e,k[2],15,718787259);e=l(e,d,f,h,k[9],21,-343485551);a[0]=h+a[0]&4294967295;a[1]=e+a[1]&4294967295;a[2]=d+a[2]&4294967295;a[3]=f+a[3]&4294967295}function b(a,b,g,c,d,f){b=(b+a&4294967295)+(c+f&4294967295)&4294967295;return(b<<d|b>>>32-d)+g&4294967295}function c(a,g,c,e,d,f,l){return b(g&c|~g&e,a,g,d,f,l)}function g(a,g,c,e,d,f,l){return b(g&e|c&~e,a,g,d,f,l)}function l(a,g,c,e,d,f,l){return b(c^(g|~e),
a,g,d,f,l)}function m(b){var g=b,c=g.length;b=[1732584193,-271733879,-1732584194,271733878];var e;for(e=64;e<=g.length;e+=64){var d,f=g.substring(e-64,e),l=[];for(d=0;64>d;d+=4)l[d>>2]=f.charCodeAt(d)+(f.charCodeAt(d+1)<<8)+(f.charCodeAt(d+2)<<16)+(f.charCodeAt(d+3)<<24);a(b,l)}g=g.substring(e-64);d=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(e=0;e<g.length;e++)d[e>>2]|=g.charCodeAt(e)<<(e%4<<3);d[e>>2]|=128<<(e%4<<3);if(55<e)for(a(b,d),e=0;16>e;e++)d[e]=0;d[14]=8*c;a(b,d);for(g=0;g<b.length;g++){c=b[g];
e="";for(d=0;4>d;d++)e+=t[c>>8*d+4&15]+t[c>>8*d&15];b[g]=e}return b.join("")}var t="0123456789abcdef".split("");m("hello");return m}();/*
 The MIT License: Copyright (c) 2010-2017 LiosK.
*/
var L;
L=function(a){function b(){var a=c.h;this.timestamp=0;this.s=a(14);this.node=1099511627776*(a(8)|1)+a(40);this.w=a(4)}function c(){}c.Y=function(){var a=c.h,b=c.W;return b(a(32),8)+"-"+b(a(16),4)+"-"+b(16384|a(12),4)+"-"+b(32768|a(14),4)+"-"+b(a(48),12)};c.h=function(a){if(0>a||53<a)return NaN;var b=0|1073741824*Math.random();return 30<a?b+1073741824*(0|Math.random()*(1<<a-30)):b>>>30-a};c.W=function(a,b){a=a.toString(16);b-=a.length;for(var c="0";0<b;b>>>=1,c+=c)b&1&&(a=c+a);return a};c.Ha=a;(function(){var a=
c.h;c.La=function(){c.h=a};var b=null,m=a;"undefined"!==typeof window&&(b=window.crypto||window.Ga)?b.getRandomValues&&"undefined"!==typeof Uint32Array&&(m=function(a){if(0>a||53<a)return NaN;var c=b.getRandomValues(new Uint32Array(32<a?2:1));return 32<a?c[0]+4294967296*(c[1]>>>64-a):c[0]>>>32-a}):"undefined"!==typeof require&&(b=require("crypto"))&&b.xa&&(m=function(a){if(0>a||53<a)return NaN;var c=b.xa(32<a?8:4),g=c.ya(0);return 32<a?g+4294967296*(c.ya(4)>>>64-a):g>>>32-a});c.h=m})();c.da="timeLow timeMid timeHiAndVersion clockSeqHiAndReserved clockSeqLow node".split(" ");
c.ea=[32,16,16,8,8,48];c.na=function(){var a=c.h;return(new c).C(a(32),a(16),16384|a(12),128|a(6),a(8),a(48))};c.parse=function(a){if(a=/^\s*(urn:uuid:|\{)?([0-9a-f]{8})-([0-9a-f]{4})-([0-9a-f]{4})-([0-9a-f]{2})([0-9a-f]{2})-([0-9a-f]{12})(\})?\s*$/i.exec(a)){var b=a[1]||"",g=a[8]||"";if(""===b+g||"{"===b&&"}"===g||"urn:uuid:"===b.toLowerCase()&&""===g)return(new c).C(parseInt(a[2],16),parseInt(a[3],16),parseInt(a[4],16),parseInt(a[5],16),parseInt(a[6],16),parseInt(a[7],16))}return null};c.prototype.C=
function(){var a=c.da,b=c.ea,m=c.fa,t=c.W;this.K=Array(6);this.X=Array(6);this.i=Array(6);for(var p=0;6>p;p++){var k=parseInt(arguments[p]||0);this.K[p]=this.K[a[p]]=k;this.X[p]=this.X[a[p]]=m(k,b[p]);this.i[p]=this.i[a[p]]=t(k,b[p]/4)}this.version=this.K.Ka>>12&15;this.Z=this.i[0]+"-"+this.i[1]+"-"+this.i[2]+"-"+this.i[3]+this.i[4]+"-"+this.i[5];return this};c.fa=function(a,b){a=a.toString(2);b-=a.length;for(var c="0";0<b;b>>>=1,c+=c)b&1&&(a=c+a);return a};c.prototype.toString=function(){return this.Z};
c.Fa=(new c).C(0,0,0,0,0,0);c.ma=function(){null==c.H&&c.Ba();var a=(new Date).getTime(),b=c.H;a!=b.timestamp?(a<b.timestamp&&b.s++,b.timestamp=a,b.w=c.h(4)):Math.random()<c.ha&&9984>b.w?b.w+=1+c.h(4):b.s++;a=c.ga(b.timestamp);var m=a.low+b.w,t=a.sa&4095|4096;b.s&=16383;return(new c).C(m,a.wa,t,b.s>>>8|128,b.s&255,b.node)};c.Ba=function(){c.H=new b};c.ha=.25;c.H=null;c.ga=function(a){a-=Date.UTC(1582,9,15);var b=a/4294967296*1E4&268435455;return{low:1E4*(a&268435455)%4294967296,wa:b&65535,sa:b>>>
16,timestamp:a}};c.va=function(){var a=c.Y;c.Y=function(b){return b&&1==b.version?c.ma().Z:a.call(c)};c.va=function(){}};"undefined"!==typeof module&&module&&module.la&&(module.la=c);return c}(L);var M;
M={Da:function(a,b){b&&chrome.storage.local.set({app_token:a},function(){b()})},I:function(a){a&&chrome.storage.local.get("app_token",function(b){a("app_token"in b?b.app_token:null)})},za:function(a){a&&chrome.storage.local.remove("app_token",function(){a()})},F:function(a){a&&chrome.storage.local.get("app_id",function(b){if("app_id"in b)a(b.app_id);else{var c="{"+L.na()+"}";chrome.storage.local.set({app_id:c},function(){a(c)})}})},Ea:function(a,b){chrome.storage.local.set({last_used_cookie:a},function(){b()})},
qa:function(a){chrome.storage.local.get("last_used_cookie",function(b){"last_used_cookie"in b?a(b.last_used_cookie):a(null)})},Aa:function(a){chrome.storage.local.remove("last_used_cookie",function(){a()})},pa:function(a){chrome.cookies.get({url:I.ra(),name:"__auth"},function(b){b?a(b.value):a(null)})}};function N(a,b){this.b=a;this.l=b;this.ca=this.G=this.a=this.M=null;this.j={};this.j[this.g.A]=$.Callbacks();this.j[this.g.COMPLETE]=$.Callbacks()}N.prototype.g={A:"progress_change",COMPLETE:"complete"};N.prototype.B={V:"success",U:"failed"};N.prototype.getImageData=function(){return this.l};N.prototype.J=function(){var a={Ca:this.G};this.a?a.error=this.a:a.o=this.ca;return a};N.prototype.attachEvent=function(a,b){"undefined"!==typeof this.j[a]&&this.j[a].add(b)};
N.prototype.detachEvent=function(a,b){"undefined"!==typeof this.j[a]&&this.j[a].remove(b)};function O(a,b){O.S.constructor.call(this,a,b);this.N="5CE3DF4D45AC";this.ua="http://upload.prntscr.com/upload/{time}/{hash}/"}z.extend(O,N);
O.prototype.upload=function(){var a=this;this.G=this.B.U;var b=function(a){var b=a.split(",");a=b[0].match(/:(.*?);/)[1];b=atob(b[1]);for(var c=b.length,g=new Uint8Array(c);c--;)g[c]=b.charCodeAt(c);return new Blob([g],{type:a})}(a.l.dataUrl),c=new FormData;c.append("image",b,"image.png");c.append("app_id",a.l.app_id);"app_token"in a.l&&c.append("app_token",a.l.app_token);b=Math.floor(Date.now()/1E3);var g=J("{key}*{time}".replace("{key}",this.N).replace("{time}",b));b=this.ua.replace("{time}",b).replace("{hash}",
g);this.M=$.ajax({processData:!1,contentType:!1,url:b,type:"POST",timeout:18E4,data:c,xhr:function(){var b=new XMLHttpRequest;b.upload.onprogress=function(b){b.lengthComputable&&a.j[a.g.A].fire({loaded:b.loaded,total:b.total})};return b},beforeSend:function(){},complete:function(b,c){a.G=a.B.U;try{var g=$.parseXML(b.responseText);if(g&&(g.getElementsByTagName("url").length||g.getElementsByTagName("share").length)){a.G=a.B.V;var l={};g&&(g.getElementsByTagName("url").length&&g.getElementsByTagName("url")[0].innerHTML&&
(l.img_url=g.getElementsByTagName("url")[0].innerHTML),g.getElementsByTagName("thumb").length&&g.getElementsByTagName("thumb")[0].innerHTML&&(l.thumb_url=g.getElementsByTagName("thumb")[0].innerHTML),g.getElementsByTagName("share").length&&g.getElementsByTagName("share")[0].innerHTML&&(l.share_url=g.getElementsByTagName("share")[0].innerHTML),l.width=0,l.height=0,l.delete_hash="");a.ca=l}else a.a=A.u("screenshot_plugin_image_hosting_incorrect_response")}catch(k){a.a=A.u("screenshot_plugin_upload_error_capt")+
"\n\n",a.a+=A.u("screenshot_plugin_upload_error_detailed_info")+":\n",a.a+="status = "+(b&&b.status?b.status:"")+"\n",a.a+="textStatus = "+c+"\n",a.a+="e = "+k+"\n",a.a+="responseText = "+(b&&b.responseText?b.responseText:"")+"\n"}a.j[a.g.COMPLETE].fire(a.J())}})};O.prototype.cancel=function(){this.M&&this.M.abort()};O.prototype.J=function(){var a=O.S.J.apply(this,arguments);a.key=this.N.substr(this.N.length-4);return a};function P(a,b){this.b=a;this.l=b;var c=this;this.L=[];this.L.push(function(){return new O(c.b,c.l)});this.O=0;this.P=this.R=this.ba=this.aa=this.c=null}function da(a){a.R=function(b){ea(a,b)};a.c.attachEvent(a.c.g.COMPLETE,a.R);a.P=function(b){C.sendMessage({name:Q,id:a.b,progress:Math.round(b.loaded/b.total*100)})};a.c.attachEvent(a.c.g.A,a.P)}function R(a){a.c.detachEvent(a.c.g.COMPLETE,a.R);a.c.detachEvent(a.c.g.A,a.P)}
P.prototype.upload=function(){this.c=this.L[this.O]();da(this);T.f("upload","hosting","attempt");this.c.upload()};function ea(a,b){b.Ca===a.c.B.V?("share_url"in b.o?U(a,{url:b.o.share_url,success:!0}):(a.aa=b.o.img_url,b.o.dpr=a.l.dpr,T.f("upload","prntscr","attempt"),M.F(function(c){M.I(function(g){b.o.app_id=c;g&&(b.o.app_token=g);I.save(b.o,function(b){U(a,b)})})})),T.f("upload","hosting","success_"+b.key)):(T.f("upload","hosting","fail_"+b.key),fa(a));T.f("upload","hosting","finished")}
function fa(a){a.O++;a.O<a.L.length?(R(a),a.c=null,a.upload()):(C.sendMessage({name:V,id:a.b}),T.f("upload","totalfail"))}function U(a,b){b&&b.success&&b.url?(a.ba=b.url,T.f("upload","prntscr","success")):T.f("upload","prntscr","fail");C.sendMessage({name:W,id:a.b});T.f("upload","prntscr","finished")}P.prototype.cancel=function(){this.c.cancel();R(this);T.f("upload","cancel")};function X(){this.m={}}
X.prototype.upload=function(a,b){this.m[a]=new P(a,b);this.m[a].upload();C.sendMessage({name:Y,id:a});T.f("upload","attempt")};function Z(a,b){a.m[b]?(a=a.m[b],a=a.ba||a.aa):a=null;return a};var H="upload_screenshot",Y="upload_started",Q="upload_progress",W="upload_success",V="upload_failed",E="open_screenshot_link",G="copy_screenshot_link",F="cancel_upload";var T=function(a){(function(){window._gaq.push(["_setAccount",a]);window._gaq.push(["_trackPageview"]);var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src="https://ssl.google-analytics.com/ga.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)})();return{f:function(a,c,g,l,m){window._gaq.push(["_trackEvent",a,c,g,l,m])}}}("UA-53060756-1"),C=function(){function a(a){a.clipboardData.setData("text/plain",S);a.preventDefault()}function b(a,
b,c){if(a&&"undefined"!==typeof a&&"undefined"!==typeof a.name)switch(a.name){case "load_screenshot":a=a.id;b=K[a];delete K[a];c(b);break;case H:l(a.id);c();break;case "close_screenshot_window":chrome.tabs.remove(b.tab.id)}}function c(a){g(a,function(){if(D[a]&&D[a].cmdAfterUpload){var b=Z(d,a);switch(D[a].cmdAfterUpload){case "search_google":chrome.tabs.create({url:"http://www.google.com/searchbyimage?image_url="+b+"/direct"});break;case "share_twitter":chrome.tabs.create({url:"http://twitter.com/home?source=Lightshot&status="+
b+"%20"});break;case "share_facebook":chrome.tabs.create({url:"https://www.facebook.com/dialog/share?app_id=585941498129307&display=page&href="+b+"&redirect_uri="+b});break;case "share_vk":chrome.tabs.create({url:"http://vk.com/share.php?url="+b});break;case "share_pinterest":chrome.tabs.create({url:"http://pinterest.com/pin/create/button/?url="+b+"&media="+b+"/direct"})}f.D(a)}else f.T(a,{type:"success",message:Z(d,a)})})}function g(a,b){chrome.storage.local.remove(a,function(){b&&b()})}function l(a){k(function(){chrome.storage.local.get(a,
function(b){var c=b[a];D[a]=c;M.F(function(b){M.I(function(e){c.app_id=b;e&&("cmdAfterUpload"in c&&"search_google"===c.cmdAfterUpload||(c.app_token=e));d.upload(a,c)})})})})}function m(a){t(a)}function t(){p(function(a){var b=ba.oa("screenshot_");K[b]=a;chrome.tabs.create({url:chrome.extension.getURL("screenshot.html?id="+b)},function(a){if("function"==typeof chrome.tabs.setZoom)try{chrome.tabs.setZoom(a.id,1)}catch(ha){}})})}function p(a){chrome.tabs.captureVisibleTab({format:"png"},function(b){a(b)})}
function k(a){M.pa(function(b){b?M.qa(function(c){c&&c===b?a&&a():e(b,a)}):h(a())})}function h(a){M.I(function(b){b?M.F(function(c){I.ka(c,b,function(){M.za(function(){M.Aa(function(){a&&a()})})})}):a&&a()})}function e(a,b){M.F(function(c){chrome.runtime.getPlatformInfo(function(d){d="{os} {arch}".replace("{os}",d.os).replace("{arch}",d.arch);I.ia(a,c,d,function(c){!0===c.success&&"app_token"in c&&""!==c.app_token?M.Ea(a,function(){M.Da(c.app_token,function(){b&&b()})}):b&&b()})})})}var d=null,f=
null,S=null,D={},K={};return{ta:function(){d=new X;f=ca();chrome.browserAction.onClicked.addListener(m);chrome.runtime.onMessage.addListener(b);document.addEventListener("copy",a);var c=chrome.runtime.getManifest().version;"undefined"===typeof window.localStorage.lightshot_version?window.localStorage.ever_updated="no":window.localStorage.lightshot_version!=c&&(window.localStorage.ever_updated="yes");window.localStorage.lightshot_version=c},sendMessage:function(a){if(a&&"undefined"!==typeof a&&"undefined"!==
typeof a.name)switch(a.name){case Y:f.ja(a.id);break;case Q:f.T(a.id,{type:"progress",progress:a.progress});break;case W:c(a.id);break;case V:f.T(a.id,{type:"failed"});break;case E:chrome.tabs.create({url:Z(d,a.id)});f.D(a.id);break;case G:S=Z(d,a.id);document.execCommand("copy");f.D(a.id);break;case F:g(a.id,function(){var b=d,c=a.id;b.m[c]&&(b.m[c].cancel(),delete b.m[c])}),f.D(a.id)}}}}();C.ta();
